version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5433:5432"  # ホスト側のポートを5433に変更
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432  # コンテナ内のポートは5432のまま
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  pgdata:
